### PR TITLE
[TASK] ConfigurationApi

### PR DESCRIPTION
**Pull request by achimfritz**

### CODE REVIEW

**Comment by achimfritz** [comment]
Dear CoreAPI developers, can you please enforce merging this pull request? It is already 9 Month old, and have a year on waiting

**Comment by etobi** [comment]
Sorry for the delay. I'll check your PR next week. Poke me if i dont.

**Comment by etobi** [comment]
manually merged into master.

**Comment by etobi** [comment]
I haven't followed our release workflow. So I
* reverted the merge in master with 047ded6 / 413e560 and
* merged in develop@d1a8fb7

**Pull request closed without merging**
